mkdir build
cd ./build
rem Generate VS2019 project.
cmake ../ -DFLAGGG_WIN32_CONSOLE=1 -DFLAGGG_D3D11=1 -DFLAGGG_NO_BOOST=0 -DFLAGGG_LIB_TYPE="SHARED" -DFLAGGG_NO_BOOST=1 -DFLAGGG_PROTO=0 -Dprotobuf_BUILD_TESTS=OFF -G "Visual Studio 16"
pause
