mkdir build
cd ./build
rem Generate VS2019 project.
cmake ../ -DFLAGGG_WIN32_CONSOLE=1 -DFLAGGG_D3D11=1 -DFLAGGG_OPENGL=1 -DFLAGGG_VULKAN=1 -DFLAGGG_METAL=0 -DFLAGGG_NO_BOOST=0 -DFLAGGG_LIB_TYPE="SHARED" -DFLAGGG_NO_BOOST=1 -DFLAGGG_PROTO=1 -Dprotobuf_BUILD_TESTS=OFF -DFLAGGG_PHYSICS=0 -DFLAGGG_CSHARP_MODULE=0 -G "Visual Studio 17"
pause
