#!/bin/bash
mkdir build
cd ./build
cmake ../ -G "Unix Makefiles" -DFLAGGG_WIN32_CONSOLE=1 -DFLAGGG_D3D11=0 -DFLAGGG_OPENGL=0 -DFLAGGG_VULKAN=0 -DFLAGGG_METAL=1 -DFLAGGG_LIB_TYPE="STATIC" -DFLAGGG_NO_BOOST=1 -DFLAGGG_PROTO=1 -Dprotobuf_BUILD_TESTS=OFF -DFLAGGG_PHYSICS=0 -DFLAGGG_JOLT=0 -DFLAGGG_PHYSX=0 -DCROSS_PLATFORM_DETERMINISTIC=ON -DFLAGGG_CSHARP_MODULE=0
