language: cpp

matrix:
    include:
        - compiler: clang
          os: osx
          env: arch=x86_64 platform=osx

        - compiler: clang
          os: osx
          env: arch=arm platform=ios

        - compiler: clang
          os: osx
          env: arch=arm platform=tvos

        - compiler: clang
          os: linux

script:
    - "scripts/build_${TRAVIS_OS_NAME}.sh"

notifications:
    email: false

